VESPUCCI_BASE_URL = "https://dev.stm-vespucci.com"
JOBCONTROL_API_BASE_URL = f"{VESPUCCI_BASE_URL}/svc/jobcontrol/v1alpha1"
JOBCONTROL_API_JOBS_ENDPOINT = f"{JOBCONTROL_API_BASE_URL}/jobs"
TRAINING_JOB_TEMPLATE_ID = "01H946MMCDK6BTJDJH98RE4YWC"
CUBEAI_JOB_TEMPLATE_ID = "01HC4FTDRWBCK31YXMGW06HV5Z"
COMPILATION_JOB_TEMPLATE_ID = "01HA84RJZMXA0Z0ZDRW6WEVM05"

JOB_POLLING_INTERVAL_SECS = 1