general:
  project_name: handposture
  logs_dir: logs
  saved_models_dir: saved_models

train_parameters:
  batch_size: 32
  training_epochs: 1000
  optimizer: adam
  initial_learning: 0.01
  learning_rate_scheduler: reducelronplateau

dataset:
  name: ST_handposture_dataset
  class_names: [None, Like, Dislike, FlatHand, Fist, Love, BreakTime, CrossHands]
  training_path: datasets/ST_VL53L8CX_handposture_dataset
  validation_path: #datasets/ST_VL53L8CX_handposture_test
  test_path: 

pre_processing:
  Max_distance: 400
  Min_distance: 100
  Background_distance: 120

data_augmentation:
  RandomFlip: horizontal

model:
  model_type: {name : CNN2D_ST_HandPosture, version : v1}
  input_shape: [8, 8, 2]
  dropout: 0.5

stm32ai:
  version: 8.1.0
  optimization: balanced
  footprints_on_target: STM32L4R9I-DISCO
  path_to_stm32ai: C:/Work/AI/Cube.AI/8.1.0/windows/stm32ai.exe
  
mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}