general:
  project_name: Pascal_VOC_2012_Demo
  logs_dir: logs
  saved_models_dir: saved_models

train_parameters:
  batch_size: 64
  training_epochs: 50
  optimizer: adam
  initial_learning: 0.001
  learning_rate_scheduler: reducelronplateau

  ### Reply config extension
  early_stopping:
    patience: 2
  model_checkpoint:
    save_best_only: False

dataset:
  name: Pascal_VOC_2012
  # class_names: [person]
  class_names:
    - aeroplane 
    - bicycle 
    - bird 
    - boat 
    - bottle 
    - bus 
    - car 
    - cat 
    - chair 
    - cow 
    - diningtable 
    - dog 
    - horse 
    - motorbike 
    - person 
    - pottedplant 
    - sheep 
    - sofa 
    - train 
    - tvmonitor
  training_path: /hd0/lavoro/st-vespucci/datasets/pascal-voc-2012/train-trimmed
  validation_path: /hd0/lavoro/st-vespucci/datasets/pascal-voc-2012/valid-trimmed
  test_path: 

pre_processing:
  rescaling: {scale : 127.5, offset : -1}
  resizing: bilinear
  aspect_ratio: False
  color_mode: rgb

post_processing:
  confidence_thresh: 0.01
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.4

data_augmentation:
  augment: True
  rotation: 30
  shearing: 15
  translation: 0.1
  vertical_flip: 0.5
  horizantal_flip: 0.2
  gaussian_blur: 3.0
  linear_contrast: [0.75, 1.5]

model:
  model_type: {name : mobilenet, version : v1, alpha : 0.25} 
  input_shape: [192,192, 3]
  transfer_learning : True

quantization:
  quantize: True
  evaluate: False
  quantization_dataset:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  version: 7.3.0
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO
  path_to_stm32ai: C:/stmicroelectronics2022/cube_ai/windows/stm32ai.exe
  
mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}